Adding postgis in Rails 6 article
BiggerPockets/blueprint pull request #15
Opened 2020-08-25 13:39 UTC by SpiderMasterMind

This is an article about adding PostGIS support to Rails 6

Any feedback is appreciated!

Run `bundle exec jekyll server --watch --drafts` to allow jekyll to serve files in the `drafts` folder so you can check out the formatting. The content column is definitely too narrow. Not sure if we want to update the styling/theme in general - thatll be for another ticket.

2020-08-25 13:42 UTC, SpiderMasterMind commented on _drafts/adding_postgis.md
> +Here at BiggerPockets Engineering, we have been busy building the first iteration of the new BPInsights Rent Estimator for Beta launch. [https://biggerpockets.com/insights/property-searches/new] [1]
NOt sure if we wanna call this Rent Estimator now or in here?

2020-08-25 13:51 UTC, lewispb requested changes
Nice! 

Just a couple minor things.

2020-08-25 13:51 UTC, lewispb commented on _drafts/adding_postgis.md
> +-    DatabaseCleaner.clean_with(:deletion, cache_tables: false, except: %w(spatial_ref_sys))
Is this diff the right way round? 🤔

2020-08-25 13:51 UTC, lewispb commented on _drafts/adding_postgis.md
> +Here at BiggerPockets Engineering, we have been busy building the first iteration of the new BPInsights Rent Estimator for Beta launch. [https://biggerpockets.com/insights/property-searches/new] [1]
Rendering this locally I'm not sure the reference style links are rendering as we intend?

<img width="615" alt="Screenshot 2020-08-25 at 14 48 29" src="https://user-images.githubusercontent.com/1773614/91182405-0b9c2000-e6e2-11ea-8a70-6d20894a32d5.png">

2020-08-25 13:51 UTC, lewispb commented on _drafts/adding_postgis.md
> +private_class_method :distance_conversion_node
```suggestion
```

I think we can omit these for clarity in our example here

2020-08-25 13:51 UTC, lewispb commented on _drafts/adding_postgis.md
> +private_class_method :st_point_node
```suggestion
```

I think we can omit these for clarity in our example here

2020-08-27 15:52 UTC, SpiderMasterMind commented on _drafts/adding_postgis.md
> +-    DatabaseCleaner.clean_with(:deletion, cache_tables: false, except: %w(spatial_ref_sys))
Nice catch 🐟

2020-08-27 15:52 UTC, SpiderMasterMind commented on _drafts/adding_postgis.md
> +private_class_method :distance_conversion_node
👍

2020-08-27 15:52 UTC, SpiderMasterMind commented on _drafts/adding_postgis.md
> +private_class_method :st_point_node
👍

2020-08-27 15:53 UTC, SpiderMasterMind commented
Fixed the links as well @lewispb

2023-07-31 19:42 UTC, closed without merging